### ISSUE TITLE
Error: Access Token not found

### ISSUE THREAD

**Issue by kinnla** [benetech/Secure-App-Generator#1]
Hi,
I am testing the secure app generater and created a custom form. Then I was asked to enter my access token. But I get the error message that my access token is not found (see screenshots).
<img width="629" alt="screen shot 2016-03-13 at 13 26 32" src="https://cloud.githubusercontent.com/assets/3518808/13728657/f7c49004-e91f-11e5-90a2-435d73dcd08c.png">
<img width="403" alt="screen shot 2016-03-13 at 13 27 29" src="https://cloud.githubusercontent.com/assets/3518808/13728656/f7c26c98-e91f-11e5-9b22-933a9921c080.png">

**Comment by johnhbenetech** [comment]
There are two versions of the server for both Martus and SecureApp (Development and Production), and you must use the same on both.

If you are using the default server setup in Martus (under Settings  > Server Settings > Server Setup > Connect to Default) please attempt to build an app using https://sag.benetech.org/.

If you are using our development Martus server (54.213.152.140 / 2375.3266.9260.1607.5307.3403.1352.1219.0930.7722) please use https://sag-qa.benetech.org/

If you are still having issues with the token please write back with the server and URL you are using. 

Thank you!

https://benetech.box.com/GettingStarted

**Comment by kinnla** [comment]
Thx John, I tried again and this time I got one step further and could start the app-generater. The progress animation started, and at around 60% of the circle I got an error. Any idea how to debug this?
<img width="465" alt="screen shot 2016-03-14 at 17 35 54" src="https://cloud.githubusercontent.com/assets/3518808/13751680/831c4d68-ea0b-11e5-8d32-d4a113128123.png">

**Comment by johnhbenetech** [comment]
Is this on sag.benetech.org?

We are making continuing changes to our back-end set-up to increase stability, so its possible that your build process was interrupted, or that we hit some capacity limitation.

My recommendation would be to simply try the process again.

If the error still persists, please share the inputs you are comfortable with (App name, icon, form XML).

We will check our logging and see if we can help diagnosed from our side.

**Comment by kinnla** [comment]
Hi, I am using http://sag-qa.benetech.org/buildingApkNext and I am following this guide: https://benetech.app.box.com/secureAppAlpha/1/4978087202/50918536865/1

I just tried again, but same result. 
<img width="828" alt="screen shot 2016-03-14 at 20 58 58" src="https://cloud.githubusercontent.com/assets/3518808/13758082/d7a9699e-ea27-11e5-8df3-d7bf7343e0be.png">
[martus-form.xml.zip](https://github.com/benetech/Secure-App-Generator/files/172768/martus-form.xml.zip)

**Comment by johnhbenetech** [comment]
Sorry you are still experiencing issues. Thank you for your patience and helping us test our beta offerings.

We just pushed some stability changes to the QA stage, so you can try again and hopefully the process will complete.

If you wanted to use the default Martus servers (instead of QA) you could try sag.benetech.org following the guide here:
https://benetech.box.com/GettingStarted

**Comment by kinnla** [comment]
Hi John, sorry for late reply, I have been in holidays. I just checked out the app generator again, and this time the app compiled and I could download and install it. However, the app crashes on my testing device (Huawei Y300-0100, Android 4.1.1).

**Comment by johnhbenetech** [comment]
If you can attach the XML of the form you used to build I can see if there is anything that sticks out to me.
